amcl:
  ros__parameters:
    use_sim_time: false
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/local
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      lookahead_dist: 1.5
      min_lookahead_dist: 0.8
      max_lookahead_dist: 3.0
      rotate_to_heading_angular_vel: 0.6
      use_velocity_scaled_lookahead_dist: true
      transform_tolerance: 0.2
planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      use_astar: true
      allow_unknown: false
waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 20
    stop_on_failure: false
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.10
      track_unknown_space: false
      plugins: ["static_layer", "inflation_layer"]
      filters: ["keepout_filter"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        subscribe_to_updates: false
        map_topic: "/keepout_mask"
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: true
        filter_info_topic: "/costmap_filter_info"
        transform_tolerance: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 10.0
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 12.0
      height: 12.0
      resolution: 0.05
      track_unknown_space: false
      plugins: ["voxel_layer", "inflation_layer"]
      filters: ["keepout_filter"]
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: true
        filter_info_topic: "/costmap_filter_info"
        transform_tolerance: 0.1
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        observation_sources: zed_points
        zed_points:
          topic: "/zed/point_cloud"
          clearing: true
          marking: true
          data_type: "PointCloud2"
          raytrace_max_range: 8.0
          obstacle_max_range: 6.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 10.0
