ekf_local:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Turn off VX because it's not robust when the wheels are spinning/on sand/slippery surfaces.
    # Turn off yaw, Vyaw because it might interfere, and watch out for drift.
    odom0: wheel/odom
    odom0_config: [true,  true,  false,
                   false, false, false,
                   false,  false, false,
                   false, false, false,
                   false, false, false]
    # x, y, z,
    # roll, pitch, yaw,
    # vx, vy, vz,
    # vroll, vpitch, vyaw,
    # ax, ay, az
    odom0_differential: false
    odom0_relative: false

    imu0: imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true,  true,  false]
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true
