navsat_transform:
  ros__parameters:
    frequency: 20.0
    delay: 0.0

    magnetic_declination_radians: 0.0   # Location-based adjust later
    yaw_offset: 0.0                     # using yaw from the IMU
    zero_altitude: true
    publish_filtered_gps: true
    use_odometry_yaw: false            # using yaw from the IMU
    wait_for_datum: false
    use_manual_datum: false
